name: rclone-sync
on:
  schedule:
    - cron: 0 */7 * * *
  workflow_dispatch:
jobs:
  rclone-syncProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Inject Rclone config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
    - name: Rclone Sync
      run: |
        rclone delete cok: --include '*.{html,url,jpg,png,srt,txt,exe,vtt,torrent,json,nfo}' --fast-list -P
